name: build release
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create py310 environment
        run: conda create --name py310 python=3.10
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: py310
