name: build release
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
      - name: Install dependencies
        run: conda install fake-bpy
