name: build release
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        # https://en.wikipedia.org/wiki/CUDA#GPUs_supported
        artifact: [
          # {
          #   arch: "75",
          #   name: "Turing",
          #   gpus: "RTX 2060 - 2080 & Ti, Quadro RTX 4000 - 8000"
          # },
          {
            arch: "86",
            name: "Ampere",
            gpus: "RTX 3050 - 3090 & Ti, RTX A2000 - A6000"
          },
          # {
          #   arch: "89",
          #   name: "Lovelace",
          #   gpus: "RTX 4070 - 4090, RTX 6000 Ada"
          # }
        ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      
      - name: Install CMake
        uses: lukka/get-cmake@v3.24.2
      
      - name: Install CUDA Toolkit
        uses: JamesPerlman/get-cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
          method: 'network'
          # https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/
          sub-packages: '["cublas_dev", "cudart", "curand_dev", "nvcc", "thrust", "visual_studio_integration"]'
      
      - name: List DLLs
        run: |
          ls "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1/bin"

      # - name: Setup Conda
      #   uses: conda-incubator/setup-miniconda@v2.2.0
      #   with:
      #     activate-environment: py310
      #     environment-file: etc/py310.yml
      #     auto-activate-base: false
      
      # - name: CMake Configure
      #   env:
      #     CUDA_ARCH_LIST: ${{ matrix.artifact.arch }}
      #     TCNN_CUDA_ARCHITECTURES: ${{ matrix.artifact.arch }}
          
      #   run: |
      #     cmake . \
      #       -B build \
      #       -G "Visual Studio 17 2022" \
      #       -A x64 \
      #       -DCMAKE_BUILD_TYPE=Release \
      #       -DPYTHON_EXECUTABLE="${CONDA_PREFIX}\\python.exe" \
      #       -DTN_BUILD_PYD=ON \
      #       -DTN_BUILD_EXE=OFF

      # - name: CMake Build
      #   run: cmake --build build --config Release -j
      
      # - name: Archive Build Result
      #   uses: thedoctor0/zip-release@0.7.1
      #   with:
      #     type: 'zip'
      #     path: build/Release/
      #     filename: 'TurboNeRF-${{ matrix.artifact.name }}.zip'

      # - name: Upload Binaries
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true
      #     body: 'Binary for NVIDIA ${{ matrix.artifact.name }} GPUs: ${{ matrix.artifact.gpus }}'
      #     bodyFile: 'TurboNeRF-${{ matrix.artifact.name }}.zip'
      #     commit: ${{ github.sha }}
      #     makeLatest: true
      #     name: 'TurboNeRF Pre-Release (${{ matrix.artifact.name }})'
      #     prerelease: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
