name: build release
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      
      - name: Install CMake
        uses: lukka/get-cmake@v3.24.2
      
      - name: Install CUDA Toolkit
        uses: JamesPerlman/get-cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
          method: 'network'

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: py310
          environment-file: etc/py310.yml
          auto-activate-base: false
      
      - name: Configure CMake
        shell: bash
        env:
          CUDA_ARCH_LIST: 75;80;86;87;89;90;90a
          TCNN_CUDA_ARCHITECTURES: 75;80;86;87;89;90;90a
        run: cmake . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TurboNeRF
          path: build/Release/
