name: build release
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: py310
          environment-file: etc/py310.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
